# Generated by Django 5.0.4 on 2024-04-30 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('luggage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_status1', models.BooleanField()),
                ('is_status2', models.BooleanField()),
                ('is_status3', models.BooleanField()),
                ('is_status4', models.BooleanField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
